# Generated by Django 6.1 on 2026-08-08 19:47

import django.core.validators
import django.db.models.deletion
import tracks.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to=tracks.models.track_source_path)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VOCALS', 'Vocals'), ('DRUMS', 'Drums'), ('BASS', 'Bass'), ('GUITAR', 'Guitar'), ('PIANO', 'Piano'), ('OTHER', 'Other'), ('INSTRUMENTAL', 'Instrumental'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('file', models.FileField(upload_to=tracks.models.stem_path)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='tracks.track')),
            ],
            options={
                'ordering': ['type'],
                'constraints': [models.UniqueConstraint(fields=('track', 'type'), name='unique_track_stem_type')],
            },
        ),
    ]
