# Generated by Django 5.2.15 on 2026-09-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='source_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
