"""
Django settings for resonance project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os


def load_local_environment(path: Path) -> None:
    """Load a simple root .env without overriding the real process environment."""
    if not path.is_file():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        if key and key not in os.environ:
            os.environ[key] = value.strip().strip('"').strip("'")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_local_environment(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes'}

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracks',
    'processing',
    'analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'resonance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resonance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
TELEO_SEPARATOR_MODEL = os.environ.get('TELEO_SEPARATOR_MODEL', 'htdemucs_6s.yaml')
VOCAL_SEPARATOR_MODEL = os.environ.get('VOCAL_SEPARATOR_MODEL', 'UVR-MDX-NET-Inst_HQ_4.onnx')
# Backwards-compatible alias for integrations that still read the old setting.
AUDIO_SEPARATOR_DEFAULT_MODEL = TELEO_SEPARATOR_MODEL
_audio_separator_model_dir = Path(os.environ.get('AUDIO_SEPARATOR_MODEL_DIR', BASE_DIR / 'var' / 'models' / 'audio-separator'))
AUDIO_SEPARATOR_MODEL_DIR = _audio_separator_model_dir if _audio_separator_model_dir.is_absolute() else BASE_DIR / _audio_separator_model_dir
VOCAL_ISOLATION_PRESET = os.environ.get('VOCAL_ISOLATION_PRESET', 'vocal_clean')
VOCAL_ISOLATION_CPU_FALLBACK = os.environ.get('VOCAL_ISOLATION_CPU_FALLBACK', 'true').lower() in {'1', 'true', 'yes'}
VOCAL_ISOLATION_FALLBACK_ALLOWED = os.environ.get('VOCAL_ISOLATION_FALLBACK_ALLOWED', 'true').lower() in {'1', 'true', 'yes'}
VOCAL_ISOLATION_REQUIRED = os.environ.get('VOCAL_ISOLATION_REQUIRED', 'false').lower() in {'1', 'true', 'yes'}
VOCAL_REFINEMENT_ENABLED = os.environ.get('VOCAL_REFINEMENT_ENABLED', 'false').lower() in {'1', 'true', 'yes'}
VOCAL_REFINEMENT_MAX_PASSES = min(2, max(1, int(os.environ.get('VOCAL_REFINEMENT_MAX_PASSES', '2'))))
VOCAL_COMPARISON_ENABLED = os.environ.get('VOCAL_COMPARISON_ENABLED', 'false').lower() in {'1', 'true', 'yes'}
MAX_UPLOAD_SIZE_MB = int(os.environ.get('MAX_UPLOAD_SIZE_MB', '250'))

# Optional automatic drum transcription. ADTOF is imported only while a drums
# analysis is running, so Django and manual review remain usable without it.
DRUM_TRANSCRIPTION_BACKEND = os.environ.get('DRUM_TRANSCRIPTION_BACKEND', 'adtof')
DRUM_TRANSCRIPTION_DEVICE = os.environ.get('DRUM_TRANSCRIPTION_DEVICE', 'auto')
DRUM_TRANSCRIPTION_ENABLED = os.environ.get('DRUM_TRANSCRIPTION_ENABLED', 'True').lower() in {'1', 'true', 'yes'}
DRUM_EVENT_MATCH_TOLERANCE_MS = int(os.environ.get('DRUM_EVENT_MATCH_TOLERANCE_MS', '50'))

# Musical post-processing. Every value can be tuned without changing algorithms.
BASS_POST_MAX_GAP_MS = int(os.environ.get('BASS_POST_MAX_GAP_MS', '80'))
BASS_POST_MIN_DURATION_MS = int(os.environ.get('BASS_POST_MIN_DURATION_MS', '60'))
BASS_POST_MIN_CONFIDENCE = float(os.environ.get('BASS_POST_MIN_CONFIDENCE', '0.50'))
GUITAR_POST_MAX_GAP_MS = int(os.environ.get('GUITAR_POST_MAX_GAP_MS', '60'))
GUITAR_POST_MIN_DURATION_MS = int(os.environ.get('GUITAR_POST_MIN_DURATION_MS', '45'))
GUITAR_POST_MIN_CONFIDENCE = float(os.environ.get('GUITAR_POST_MIN_CONFIDENCE', '0.50'))
PITCH_MERGE_TOLERANCE_CENTS = float(os.environ.get('PITCH_MERGE_TOLERANCE_CENTS', '50'))
POSTPROCESS_INTENSITY_MODE = os.environ.get('POSTPROCESS_INTENSITY_MODE', 'max')
VOCALS_POST_HEARTBEAT_MS = int(os.environ.get('VOCALS_POST_HEARTBEAT_MS', '200'))
OTHER_POST_HEARTBEAT_MS = int(os.environ.get('OTHER_POST_HEARTBEAT_MS', '200'))
DRUM_REFRACTORY_KICK_MS = int(os.environ.get('DRUM_REFRACTORY_KICK_MS', '90'))
DRUM_REFRACTORY_SNARE_MS = int(os.environ.get('DRUM_REFRACTORY_SNARE_MS', '70'))
DRUM_REFRACTORY_HI_HAT_MS = int(os.environ.get('DRUM_REFRACTORY_HI_HAT_MS', '35'))
DRUM_REFRACTORY_TOM_MS = int(os.environ.get('DRUM_REFRACTORY_TOM_MS', '70'))
DRUM_REFRACTORY_CRASH_MS = int(os.environ.get('DRUM_REFRACTORY_CRASH_MS', '150'))
DRUM_REFRACTORY_CYMBAL_MS = int(os.environ.get('DRUM_REFRACTORY_CYMBAL_MS', '120'))
REVIEW_MERGE_MAX_GAP_MS = int(os.environ.get('REVIEW_MERGE_MAX_GAP_MS', '250'))
DRUM_AUDITION_BEFORE_MS = int(os.environ.get('DRUM_AUDITION_BEFORE_MS', '150'))
DRUM_AUDITION_AFTER_MS = int(os.environ.get('DRUM_AUDITION_AFTER_MS', '350'))
RHUBARB_ENABLED = os.environ.get('RHUBARB_ENABLED', 'true').lower() in {'1', 'true', 'yes'}
# Empty means automatic resolution: bundled project binary, then PATH.
RHUBARB_BINARY = os.environ.get('RHUBARB_BINARY', '').strip()
RHUBARB_RECOGNIZER = os.environ.get('RHUBARB_RECOGNIZER', 'phonetic')
RHUBARB_EXTENDED_SHAPES = os.environ.get('RHUBARB_EXTENDED_SHAPES', 'GHX')
RHUBARB_TIMEOUT_SECONDS = int(os.environ.get('RHUBARB_TIMEOUT_SECONDS', '120'))
LIPSYNC_REQUIRED = os.environ.get('LIPSYNC_REQUIRED', 'true').lower() in {'1', 'true', 'yes'}
VOCAL_LANGUAGE = os.environ.get('VOCAL_LANGUAGE', 'es')
MOUTH_PREVIEW_TRANSITION_MS = int(os.environ.get('MOUTH_PREVIEW_TRANSITION_MS', '70'))
VOCAL_AUDITION_BEFORE_MS = int(os.environ.get('VOCAL_AUDITION_BEFORE_MS', '100'))
VOCAL_AUDITION_AFTER_MS = int(os.environ.get('VOCAL_AUDITION_AFTER_MS', '100'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
