# Generated by Django 6.1 on 2026-08-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='profile',
            field=models.CharField(choices=[('TELEO_6_STEM', 'Teleo Music — 6 stems'), ('VOCAL_EXTRACTION', 'Vocal extraction — Vocals + Instrumental')], default='TELEO_6_STEM', max_length=24),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('SEPARATING', 'Separating instruments'), ('ANALYZING', 'Analyzing drums'), ('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='tracks.track'),
        ),
    ]
