# Generated by Django 6.1 on 2026-08-08 19:47

import analysis.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DRUMS', 'Drums'), ('BASS', 'Bass'), ('VOCALS', 'Vocals'), ('PIANO', 'Piano'), ('GUITAR', 'Guitar'), ('TIMELINE', 'Timeline'), ('VISEMES', 'Visemes'), ('HAPTICS', 'Haptics')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('json_file', models.FileField(upload_to=analysis.models.artifact_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_artifacts', to='tracks.stem')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_artifacts', to='tracks.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('track', 'type', 'version'), name='unique_track_artifact_version')],
            },
        ),
    ]
