# Generated by Django 6.1 on 2026-08-08 23:06

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_artifacts_to_latest_job(apps, schema_editor):
    AnalysisArtifact = apps.get_model('analysis', 'AnalysisArtifact')
    ProcessingJob = apps.get_model('processing', 'ProcessingJob')
    for artifact in AnalysisArtifact.objects.filter(processing_job__isnull=True):
        job = ProcessingJob.objects.filter(track_id=artifact.track_id).order_by('-created_at').first()
        if job:
            artifact.processing_job_id = job.id
            artifact.save(update_fields=['processing_job'])


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('processing', '0003_preserve_existing_job_profiles'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysisartifact',
            name='unique_track_artifact_version',
        ),
        migrations.AddField(
            model_name='analysisartifact',
            name='processing_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_artifacts', to='processing.processingjob'),
        ),
        migrations.RunPython(assign_existing_artifacts_to_latest_job, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='analysisartifact',
            name='type',
            field=models.CharField(choices=[('DRUMS', 'Drums'), ('BASS', 'Bass'), ('VOCALS', 'Vocals'), ('PIANO', 'Piano'), ('GUITAR', 'Guitar'), ('OTHER', 'Other'), ('TELEO_EXPERIENCE', 'Teleo Experience'), ('TIMELINE', 'Timeline'), ('VISEMES', 'Visemes'), ('HAPTICS', 'Haptics')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='analysisartifact',
            constraint=models.UniqueConstraint(fields=('processing_job', 'type', 'version'), name='unique_job_artifact_version'),
        ),
    ]
