# Generated by Django 6.1 on 2026-08-08 23:12

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisartifact_processing_job_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisartifact',
            name='json_file',
            field=models.FileField(max_length=255, upload_to=analysis.models.artifact_path),
        ),
    ]
