# Generated by Django 6.1 on 2026-08-08 23:45

from django.db import migrations, models


def mark_existing_final_artifacts(apps, schema_editor):
    AnalysisArtifact = apps.get_model('analysis', 'AnalysisArtifact')
    AnalysisArtifact.objects.filter(type='TELEO_EXPERIENCE').update(stage='FINAL')


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_analysisartifact_json_file'),
        ('processing', '0003_preserve_existing_job_profiles'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysisartifact',
            name='unique_job_artifact_version',
        ),
        migrations.AddField(
            model_name='analysisartifact',
            name='stage',
            field=models.CharField(choices=[('RAW', 'Raw'), ('PROCESSED', 'Processed'), ('FINAL', 'Final')], default='RAW', max_length=12),
        ),
        migrations.RunPython(mark_existing_final_artifacts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='analysisartifact',
            constraint=models.UniqueConstraint(fields=('processing_job', 'type', 'stage', 'version'), name='unique_job_stage_artifact_version'),
        ),
    ]
