# Generated by Django 6.1 on 2026-08-09 00:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_analysisartifact_unique_job_artifact_version_and_more'),
        ('processing', '0003_preserve_existing_job_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisartifact',
            name='stage',
            field=models.CharField(choices=[('RAW', 'Raw'), ('PROCESSED', 'Processed'), ('REVIEWED', 'Reviewed'), ('FINAL', 'Final')], default='RAW', max_length=12),
        ),
        migrations.AlterField(
            model_name='analysisartifact',
            name='type',
            field=models.CharField(choices=[('DRUMS', 'Drums'), ('BASS', 'Bass'), ('VOCALS', 'Vocals'), ('PIANO', 'Piano'), ('GUITAR', 'Guitar'), ('OTHER', 'Other'), ('TELEO_EXPERIENCE', 'Teleo Experience'), ('TELEO_REVIEWED', 'Reviewed Teleo Experience'), ('TIMELINE', 'Timeline'), ('VISEMES', 'Visemes'), ('HAPTICS', 'Haptics')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('drums', 'Drums'), ('bass', 'Bass'), ('guitar', 'Guitar'), ('piano', 'Piano'), ('vocals', 'Vocals'), ('other', 'Other')], max_length=12)),
                ('event_id', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(choices=[('DELETE', 'Delete'), ('ADD', 'Add'), ('RELABEL', 'Relabel'), ('MOVE', 'Move'), ('RESIZE', 'Resize'), ('CHANGE_INTENSITY', 'Change intensity'), ('CHANGE_PITCH', 'Change pitch'), ('MERGE', 'Merge'), ('SPLIT', 'Split'), ('CONFIRM', 'Confirm'), ('MARK_RANGE', 'Mark range')], max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='analysis.reviewaction')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('review_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cursor_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analysis.reviewaction')),
                ('processing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='processing.processingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='review_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='analysis.reviewsession'),
        ),
        migrations.AddConstraint(
            model_name='reviewsession',
            constraint=models.UniqueConstraint(fields=('processing_job', 'review_version'), name='unique_job_review_version'),
        ),
        migrations.AddConstraint(
            model_name='reviewaction',
            constraint=models.UniqueConstraint(fields=('review_session', 'sequence'), name='unique_review_action_sequence'),
        ),
    ]
