# Generated by Django 6.1 on 2026-08-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_analysisartifact_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaction',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='action_type',
            field=models.CharField(choices=[('DELETE', 'Delete'), ('ADD', 'Add'), ('RELABEL', 'Relabel'), ('ASSIGN_DRUM_PIECE', 'Assign drum piece'), ('MOVE', 'Move'), ('RESIZE', 'Resize'), ('CHANGE_INTENSITY', 'Change intensity'), ('CHANGE_PITCH', 'Change pitch'), ('MERGE', 'Merge'), ('SPLIT', 'Split'), ('CONFIRM', 'Confirm'), ('MARK_RANGE', 'Mark range')], max_length=24),
        ),
    ]
