# Generated by Django 6.1 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_reviewaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewaction',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='analysis.reviewaction',
            ),
        ),
    ]
