# Generated by Django 6.1 on 2026-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_reviewaction_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewaction',
            name='action_type',
            field=models.CharField(choices=[('DELETE', 'Delete'), ('ADD', 'Add'), ('RELABEL', 'Relabel'), ('ASSIGN_DRUM_PIECE', 'Assign drum piece'), ('CONFIRM_DRUM_PIECE', 'Confirm drum piece'), ('CONFIRM_VISEME', 'Confirm viseme'), ('CHANGE_VISEME', 'Change viseme'), ('MOVE', 'Move'), ('RESIZE', 'Resize'), ('CHANGE_INTENSITY', 'Change intensity'), ('CHANGE_PITCH', 'Change pitch'), ('MERGE', 'Merge'), ('SPLIT', 'Split'), ('CONFIRM', 'Confirm'), ('MARK_RANGE', 'Mark range')], max_length=24),
        ),
    ]
