# Generated by Django 5.2.15 on 2026-09-13 19:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_add_viseme_review_actions'),
        ('processing', '0005_add_vocal_accessibility_options'),
        ('tracks', '0002_track_source_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleoPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('schema_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('quality', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('HUMAN_REVIEWED', 'Human reviewed'), ('TELEO_MASTER', 'Teleo master')], default='AUTOMATIC', max_length=20)),
                ('lyrics_included', models.BooleanField(default=False)),
                ('source_hash', models.CharField(max_length=64)),
                ('canonical_checksum', models.CharField(max_length=64)),
                ('experience_checksum', models.CharField(max_length=64)),
                ('destination_root', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField()),
                ('processing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleo_publications', to='processing.processingjob')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleo_publications', to='analysis.analysisartifact')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleo_publications', to='tracks.track')),
            ],
            options={
                'ordering': ['-experience_version'],
                'constraints': [models.UniqueConstraint(fields=('track', 'experience_version'), name='unique_track_experience_version')],
            },
        ),
    ]
